#!/bin/bash


years=("2018")
processes=("SpinHalf_DrellYan")
masses=("2000")
#masses=("1500" "2000" "2500" "3000" "3500" "4000" "4500")


for year in "${years[@]}"
do
   for process in "${processes[@]}"
   do
      logfile="log_${year}_${process}_PFMET.log"
      echo "Execution started at $(date)" > "$logfile"

      for mass in "${masses[@]}"
      do
         echo "Running for year: $year, mass: $mass, process: $process" >> "$logfile"
         root -l -q "/afs/cern.ch/user/t/tmenezes/work/private/MonopoleAnalysis_Framework/CMSSW_10_6_23/src/MonoAnalyzerPhoton/src/MonoAnalyzerPhoton.cc(\"$year\",\"$mass\",\"$process\",1 ,0)" >> $logfile        
      done

      echo "Execution finished at $(date)" >> "$logfile"
   done
done
