#!/bin/bash

#years=("2018" "2017" "2016" "2016APV")
#masses=("1000" "1500" "2000" "2500" "3000" "3500" "4000" "4500")

years=("2018")
masses=("2000")
process=("SpinHalf_PhotonFusion")
#masses=("1000" "1500" "2000" "2500" "3000" "3500" "4000" "4500")



logfile="execution_log.txt"
echo "Execution started at $(date)" > "$logfile"

for year in "${years[@]}"
do
   for mass in "${masses[@]}"
   do
      for process in "${processes[@]}"
      do
         echo "Running for year: $year, mass: $mass, process: $process" | tee -a "$logfile"
         #root -l -q "/afs/cern.ch/user/t/tmenezes/work/private/MonopoleAnalysis_Framework/CMSSW_10_6_23/src/MonoAnalyzerPhoton.cc(\"$year\",\"$mass\",\"$process\",0 ,0)" 2>&1 | tee -a "$logfile"
         root -l -q "/afs/cern.ch/user/t/tmenezes/work/private/MonopoleAnalysis_Framework/CMSSW_10_6_23/src/MonoAnalyzerPhoton.cc(\"$year\",\"$mass\",\"$process\",0 ,0)" >> $logfile
      done
   done
done

echo "Execution finished at $(date)" >> "$logfile"



